version: '3.6'

services:
  nginx:
    image: nginx:1.15.2
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    networks: 
      swarms:
        aliases:
          - nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro
    configs:
      - source: nginx-open-bioey-com.conf
        target: /etc/nginx/conf.d/open-bioey-com.conf
      - source: nginx-api-bioey-com.conf
        target: /etc/nginx/conf.d/api-bioey-com.conf
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    deploy:
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      mode: global
      placement:
        constraints: 
          - node.role == manager

networks:
  swarms:
    external: true 

configs:
  nginx-open-bioey-com.conf:
    external: true 
  nginx-api-bioey-com.conf:
    external: true 